var classes = [
    {
        "name": "hajh20\\Dice\\Game",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "playGame",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pointsGame",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resultGame",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 16,
        "ccnMethodMax": 8,
        "externals": [
            "hajh20\\Dice\\DiceHand",
            "hajh20\\Dice\\Message",
            "hajh20\\Dice\\Game",
            "hajh20\\Dice\\Game",
            "hajh20\\Dice\\Dice"
        ],
        "parents": [],
        "lcom": 3,
        "length": 233,
        "vocabulary": 62,
        "volume": 1387.33,
        "difficulty": 26.65,
        "effort": 36970.81,
        "level": 0.04,
        "bugs": 0.46,
        "time": 2054,
        "intelligentContent": 52.06,
        "number_operators": 66,
        "number_operands": 167,
        "number_operators_unique": 15,
        "number_operands_unique": 47,
        "cloc": 9,
        "loc": 79,
        "lloc": 70,
        "mi": 60.57,
        "mIwoC": 35.6,
        "commentWeight": 24.97,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 36.71,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 2.14,
        "totalSystemComplexity": 110.14,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.2,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\DiceHand",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLength",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setLength",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "roll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastRoll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "hajh20\\Dice\\Dice"
        ],
        "parents": [],
        "lcom": 1,
        "length": 59,
        "vocabulary": 16,
        "volume": 236,
        "difficulty": 14.78,
        "effort": 3487.56,
        "level": 0.07,
        "bugs": 0.08,
        "time": 194,
        "intelligentContent": 15.97,
        "number_operators": 21,
        "number_operands": 38,
        "number_operators_unique": 7,
        "number_operands_unique": 9,
        "cloc": 11,
        "loc": 48,
        "lloc": 37,
        "mi": 82.41,
        "mIwoC": 48.64,
        "commentWeight": 33.77,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 4.73,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 3.67,
        "totalSystemComplexity": 23.67,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.12,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\Bonus",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "bonus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 7,
        "volume": 28.07,
        "difficulty": 2.25,
        "effort": 63.17,
        "level": 0.44,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 12.48,
        "number_operators": 4,
        "number_operands": 6,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 16,
        "lloc": 13,
        "mi": 96.37,
        "mIwoC": 65.29,
        "commentWeight": 31.08,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\Dice",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "roll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastRoll",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 1.67,
        "effort": 30.96,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 11.15,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 18,
        "lloc": 15,
        "mi": 94.88,
        "mIwoC": 65.32,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.31,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\GraphicalDice",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "graphic",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "hajh20\\Dice\\DiceHand"
        ],
        "parents": [
            "hajh20\\Dice\\DiceHand"
        ],
        "lcom": 2,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 9,
        "loc": 22,
        "lloc": 13,
        "mi": 112.65,
        "mIwoC": 70.83,
        "commentWeight": 41.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 8.67,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\SumUp",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sumUpDices",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 26,
        "vocabulary": 15,
        "volume": 101.58,
        "difficulty": 9.71,
        "effort": 986.77,
        "level": 0.1,
        "bugs": 0.03,
        "time": 55,
        "intelligentContent": 10.46,
        "number_operators": 9,
        "number_operands": 17,
        "number_operators_unique": 8,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 17,
        "lloc": 14,
        "mi": 90.83,
        "mIwoC": 60.54,
        "commentWeight": 30.29,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\YatzyClass",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "playYatzy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 19,
        "ccnMethodMax": 19,
        "externals": [
            "hajh20\\Dice\\Dice",
            "hajh20\\Dice\\Message",
            "hajh20\\Dice\\SumUp",
            "hajh20\\Dice\\Bonus"
        ],
        "parents": [],
        "lcom": 1,
        "length": 185,
        "vocabulary": 51,
        "volume": 1049.4,
        "difficulty": 18.43,
        "effort": 19335.17,
        "level": 0.05,
        "bugs": 0.35,
        "time": 1074,
        "intelligentContent": 56.96,
        "number_operators": 51,
        "number_operands": 134,
        "number_operators_unique": 11,
        "number_operands_unique": 40,
        "cloc": 9,
        "loc": 44,
        "lloc": 35,
        "mi": 74.85,
        "mIwoC": 42.61,
        "commentWeight": 32.24,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "hajh20\\Dice\\Message",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getGameOver21Message",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "diceMessageYatzy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 7,
        "externals": [],
        "parents": [],
        "lcom": 2,
        "length": 50,
        "vocabulary": 24,
        "volume": 229.25,
        "difficulty": 3,
        "effort": 687.74,
        "level": 0.33,
        "bugs": 0.08,
        "time": 38,
        "intelligentContent": 76.42,
        "number_operators": 20,
        "number_operands": 30,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 3,
        "loc": 37,
        "lloc": 34,
        "mi": 70.2,
        "mIwoC": 48.85,
        "commentWeight": 21.35,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 11,
        "relativeSystemComplexity": 11,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 22,
        "totalSystemComplexity": 22,
        "package": "hajh20\\Dice\\",
        "pageRank": 0.1,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Index",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 11,
        "volume": 58.81,
        "difficulty": 1.44,
        "effort": 84.95,
        "level": 0.69,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 40.71,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 14,
        "lloc": 11,
        "mi": 97.62,
        "mIwoC": 64.76,
        "commentWeight": 32.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Session",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory",
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Response"
        ],
        "parents": [],
        "lcom": 2,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 1.43,
        "effort": 63.4,
        "level": 0.7,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 31.07,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 18,
        "lloc": 15,
        "mi": 92.23,
        "mIwoC": 62.68,
        "commentWeight": 29.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 50.67,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\TwigView",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 11,
        "volume": 58.81,
        "difficulty": 1.44,
        "effort": 84.95,
        "level": 0.69,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 40.71,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 14,
        "lloc": 11,
        "mi": 97.62,
        "mIwoC": 64.76,
        "commentWeight": 32.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Debug",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Response",
            "Nyholm\\Psr7\\Stream"
        ],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 1.33,
        "effort": 18.58,
        "level": 0.75,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 10.45,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 106.01,
        "mIwoC": 71.04,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Error",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "do404",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "do405",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory",
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory"
        ],
        "parents": [],
        "lcom": 2,
        "length": 38,
        "vocabulary": 17,
        "volume": 155.32,
        "difficulty": 3.11,
        "effort": 482.61,
        "level": 0.32,
        "bugs": 0.05,
        "time": 27,
        "intelligentContent": 49.99,
        "number_operators": 9,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 3,
        "loc": 21,
        "lloc": 18,
        "mi": 84.77,
        "mIwoC": 57.14,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 9.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 19.25,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Dice",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "hajh20\\Dice\\Game",
            "Nyholm\\Psr7\\Factory\\Psr17Factory",
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Response"
        ],
        "parents": [],
        "lcom": 2,
        "length": 35,
        "vocabulary": 19,
        "volume": 148.68,
        "difficulty": 2.25,
        "effort": 334.52,
        "level": 0.44,
        "bugs": 0.05,
        "time": 19,
        "intelligentContent": 66.08,
        "number_operators": 11,
        "number_operands": 24,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 3,
        "loc": 22,
        "lloc": 19,
        "mi": 83.43,
        "mIwoC": 56.36,
        "commentWeight": 27.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Sample",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "where",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 11,
        "volume": 58.81,
        "difficulty": 1.44,
        "effort": 84.95,
        "level": 0.69,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 40.71,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 14,
        "lloc": 11,
        "mi": 97.62,
        "mIwoC": 64.76,
        "commentWeight": 32.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Yatzy",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 13,
        "ccnMethodMax": 13,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "hajh20\\Dice\\YatzyClass",
            "Nyholm\\Psr7\\Factory\\Psr17Factory",
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Response"
        ],
        "parents": [],
        "lcom": 2,
        "length": 89,
        "vocabulary": 25,
        "volume": 413.3,
        "difficulty": 4.09,
        "effort": 1690.79,
        "level": 0.24,
        "bugs": 0.14,
        "time": 94,
        "intelligentContent": 101.03,
        "number_operators": 29,
        "number_operands": 60,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 3,
        "loc": 31,
        "lloc": 28,
        "mi": 71.54,
        "mIwoC": 48.36,
        "commentWeight": 23.17,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Controller\\Form",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Factory\\Psr17Factory",
            "Psr\\Http\\Message\\ResponseInterface",
            "Nyholm\\Psr7\\Response"
        ],
        "parents": [],
        "lcom": 2,
        "length": 49,
        "vocabulary": 26,
        "volume": 230.32,
        "difficulty": 2.35,
        "effort": 540.75,
        "level": 0.43,
        "bugs": 0.08,
        "time": 30,
        "intelligentContent": 98.1,
        "number_operators": 13,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 23,
        "cloc": 3,
        "loc": 21,
        "lloc": 18,
        "mi": 82.9,
        "mIwoC": 55.27,
        "commentWeight": 27.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 25.33,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 50.67,
        "package": "Mos\\Controller\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Mos\\Router\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "dispatch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 28,
        "ccn": 28,
        "ccnMethodMax": 28,
        "externals": [
            "hajh20\\Dice\\Game"
        ],
        "parents": [],
        "lcom": 1,
        "length": 202,
        "vocabulary": 52,
        "volume": 1151.49,
        "difficulty": 8.28,
        "effort": 9537.33,
        "level": 0.12,
        "bugs": 0.38,
        "time": 530,
        "intelligentContent": 139.02,
        "number_operators": 75,
        "number_operands": 127,
        "number_operators_unique": 6,
        "number_operands_unique": 46,
        "cloc": 3,
        "loc": 79,
        "lloc": 76,
        "mi": 48.64,
        "mIwoC": 33.77,
        "commentWeight": 14.87,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 6,
        "relativeSystemComplexity": 7,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 7,
        "package": "Mos\\Router\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]